package main

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestSyncMermaidExport(t *testing.T) {
	tmpDir := t.TempDir()

	// Create test model
	modelContent := `{
  "specification": {
    "elements": {
      "system": { "notation": "Software System", "container": true },
      "container": { "notation": "Container" }
    }
  },
  "model": {
    "myapp": {
      "kind": "system",
      "title": "My Application"
    }
  },
  "views": {
    "context": {
      "title": "System Context",
      "include": ["myapp"]
    }
  }
}`

	modelPath := filepath.Join(tmpDir, "architecture.jsonc")
	if err := os.WriteFile(modelPath, []byte(modelContent), 0o644); err != nil {
		t.Fatalf("failed to write model: %v", err)
	}

	// Create empty draw.io file
	drawioPath := filepath.Join(tmpDir, "architecture.drawio")
	drawioContent := `<?xml version="1.0" encoding="UTF-8"?>
<mxfile host="bausteinsicht" modified="2026-05-06T00:00:00.000Z" version="1.0">
  <diagram id="architecture" name="Architecture">
    <mxGraphModel dx="0" dy="0" gridSize="10" guides="1" tooltips="1" connect="1" arrows="1" fold="1" page="1" pageScale="1" pageWidth="827" pageHeight="1169">
      <root>
        <mxCell id="0"/>
        <mxCell id="1" parent="0"/>
      </root>
    </mxGraphModel>
  </diagram>
</mxfile>`
	if err := os.WriteFile(drawioPath, []byte(drawioContent), 0o644); err != nil {
		t.Fatalf("failed to write drawio file: %v", err)
	}

	// Create template directory with default template
	templatePath := filepath.Join(tmpDir, ".templates")
	if err := os.MkdirAll(templatePath, 0o755); err != nil {
		t.Fatalf("failed to create template dir: %v", err)
	}

	// Run sync with mermaid export
	cmd := NewRootCmd()
	mermaidOutput := filepath.Join(tmpDir, "test-arch.md")
	cmd.SetArgs([]string{
		"sync",
		"--model", modelPath,
		"--mermaid",
		"--mermaid-output", mermaidOutput,
	})

	buf := &bytes.Buffer{}
	cmd.SetOut(buf)

	// Change to tmpDir for auto-detection to work
	originalWd, _ := os.Getwd()
	_ = os.Chdir(tmpDir)
	defer func() {
		_ = os.Chdir(originalWd)
	}()

	if err := cmd.Execute(); err != nil {
		t.Logf("sync output: %s", buf.String())
		t.Fatalf("sync failed: %v", err)
	}

	// Check that mermaid file was created
	if _, err := os.Stat(mermaidOutput); err != nil {
		t.Fatalf("mermaid output file not created: %v", err)
	}

	// Read and verify mermaid content
	content, _ := os.ReadFile(mermaidOutput)
	markdown := string(content)

	if !strings.Contains(markdown, "# Architecture Diagrams") {
		t.Error("markdown missing main header")
	}
	if !strings.Contains(markdown, "Auto-generated by bausteinsicht") {
		t.Error("markdown missing metadata comment")
	}
	if !strings.Contains(markdown, "Last updated:") {
		t.Error("markdown missing timestamp")
	}
	if !strings.Contains(markdown, "System Context") {
		t.Error("markdown missing context view section")
	}
	if !strings.Contains(markdown, "```mermaid") {
		t.Error("markdown missing mermaid code block")
	}
	if !strings.Contains(markdown, "C4Context") {
		t.Error("mermaid diagram missing C4Context directive")
	}
}

func TestSyncWithoutMermaidFlag(t *testing.T) {
	tmpDir := t.TempDir()

	// Create minimal test model
	modelContent := `{
  "specification": {"elements": {}},
  "model": {},
  "views": {}
}`

	modelPath := filepath.Join(tmpDir, "architecture.jsonc")
	if err := os.WriteFile(modelPath, []byte(modelContent), 0o644); err != nil {
		t.Fatalf("failed to write model: %v", err)
	}

	// Create empty draw.io file
	drawioPath := filepath.Join(tmpDir, "architecture.drawio")
	drawioContent := `<?xml version="1.0" encoding="UTF-8"?>
<mxfile host="bausteinsicht" modified="2026-05-06T00:00:00.000Z" version="1.0">
  <diagram id="architecture" name="Architecture">
    <mxGraphModel dx="0" dy="0" gridSize="10" guides="1" tooltips="1" connect="1" arrows="1" fold="1" page="1" pageScale="1" pageWidth="827" pageHeight="1169">
      <root>
        <mxCell id="0"/>
        <mxCell id="1" parent="0"/>
      </root>
    </mxGraphModel>
  </diagram>
</mxfile>`
	if err := os.WriteFile(drawioPath, []byte(drawioContent), 0o644); err != nil {
		t.Fatalf("failed to write drawio file: %v", err)
	}

	// Run sync WITHOUT mermaid flag
	cmd := NewRootCmd()
	cmd.SetArgs([]string{"sync", "--model", modelPath})

	originalWd, _ := os.Getwd()
	_ = os.Chdir(tmpDir)
	defer func() {
		_ = os.Chdir(originalWd)
	}()

	if err := cmd.Execute(); err != nil {
		t.Fatalf("sync failed: %v", err)
	}

	// Check that default architecture.md was NOT created
	mermaidFile := filepath.Join(tmpDir, "architecture.md")
	if _, err := os.Stat(mermaidFile); err == nil {
		t.Error("architecture.md should not be created when --mermaid flag is not set")
	}
}

func TestSyncMermaidDefaultOutputPath(t *testing.T) {
	tmpDir := t.TempDir()

	// Create test model
	modelContent := `{
  "specification": {"elements": {}},
  "model": {},
  "views": {}
}`

	modelPath := filepath.Join(tmpDir, "architecture.jsonc")
	if err := os.WriteFile(modelPath, []byte(modelContent), 0o644); err != nil {
		t.Fatalf("failed to write model: %v", err)
	}

	// Create empty draw.io file
	drawioPath := filepath.Join(tmpDir, "architecture.drawio")
	drawioContent := `<?xml version="1.0" encoding="UTF-8"?>
<mxfile host="bausteinsicht" modified="2026-05-06T00:00:00.000Z" version="1.0">
  <diagram id="architecture" name="Architecture">
    <mxGraphModel dx="0" dy="0" gridSize="10" guides="1" tooltips="1" connect="1" arrows="1" fold="1" page="1" pageScale="1" pageWidth="827" pageHeight="1169">
      <root>
        <mxCell id="0"/>
        <mxCell id="1" parent="0"/>
      </root>
    </mxGraphModel>
  </diagram>
</mxfile>`
	if err := os.WriteFile(drawioPath, []byte(drawioContent), 0o644); err != nil {
		t.Fatalf("failed to write drawio file: %v", err)
	}

	// Run sync with --mermaid but without explicit output path (should use default)
	cmd := NewRootCmd()
	cmd.SetArgs([]string{
		"sync",
		"--model", modelPath,
		"--mermaid",
	})

	originalWd, _ := os.Getwd()
	_ = os.Chdir(tmpDir)
	defer func() {
		_ = os.Chdir(originalWd)
	}()

	if err := cmd.Execute(); err != nil {
		t.Fatalf("sync failed: %v", err)
	}

	// Check that default output file architecture.md was created
	defaultOutput := filepath.Join(tmpDir, "architecture.md")
	if _, err := os.Stat(defaultOutput); err != nil {
		t.Fatalf("default mermaid output file not created: %v", err)
	}
}
