package sync

import (
	"fmt"
	"html"
	"sort"
	"strconv"
	"strings"

	"github.com/beevik/etree"
	"github.com/docToolchain/Bauteinsicht/internal/drawio"
	"github.com/docToolchain/Bauteinsicht/internal/model"
)

const (
	metadataPrefix    = "metadata-"
	legendPrefix      = "legend-"
	infoBoxGap        = 80.0
	metadataX         = 40.0
	metadataWidth     = 500.0
	legendWidthRatio  = 0.30
	legendGap         = 60.0
)

// createMetadata creates or updates a metadata info box on the view page.
// Returns true if the label was created or changed.
func createMetadata(
	page *drawio.Page,
	viewID string,
	view model.View,
	cfg model.Config,
	modelPath string,
	timestamp string,
) bool {
	cellID := metadataPrefix + viewID
	label := buildMetadataLabel(view, cfg, modelPath, timestamp)

	root := page.Root()
	if root == nil {
		return false
	}

	// Update existing metadata cell — only if label actually changed.
	for _, obj := range root.SelectElements("object") {
		if obj.SelectAttrValue("id", "") == cellID {
			if obj.SelectAttrValue("label", "") == label {
				return false
			}
			obj.CreateAttr("label", label)
			return true
		}
	}

	// Create new metadata cell — 60% of content width.
	legendCellID := legendPrefix + viewID
	y := computeMaxY(page, cellID, legendCellID) + infoBoxGap
	contentWidth := computeContentWidth(page, cellID, legendCellID)
	if contentWidth < 600 {
		contentWidth = 600
	}
	width := contentWidth * 0.60
	createInfoBox(root, cellID, label, metadataX, y, width)
	return true
}

// createLegend creates or updates a legend box on the view page.
// Returns true if the label was created or changed.
func createLegend(
	page *drawio.Page,
	viewID string,
	spec model.Specification,
	templates *drawio.TemplateSet,
	elemSet map[string]bool,
	flat map[string]*model.Element,
) bool {
	cellID := legendPrefix + viewID
	label := buildLegendLabel(spec, templates, elemSet, flat)

	root := page.Root()
	if root == nil {
		return false
	}

	// Update existing legend cell — only if label actually changed.
	for _, obj := range root.SelectElements("object") {
		if obj.SelectAttrValue("id", "") == cellID {
			if obj.SelectAttrValue("label", "") == label {
				return false
			}
			obj.CreateAttr("label", label)
			return true
		}
	}

	// Create new legend cell — positioned right of the metadata box, same Y.
	metaCellID := metadataPrefix + viewID
	y := computeMaxY(page, cellID, metaCellID) + infoBoxGap

	// Compute content width for legend positioning.
	contentWidth := computeContentWidth(page, cellID, metaCellID)
	if contentWidth < 600 {
		contentWidth = 600
	}
	legendWidth := contentWidth * legendWidthRatio
	legendX := contentWidth - legendWidth + metadataX
	createInfoBox(root, cellID, label, legendX, y, legendWidth)
	return true
}

// buildMetadataLabel returns an HTML label for the metadata box.
func buildMetadataLabel(view model.View, cfg model.Config, modelPath string, timestamp string) string {
	var sb strings.Builder
	sb.WriteString("<b>")
	sb.WriteString(html.EscapeString(view.Title))
	sb.WriteString("</b>")
	if view.Description != "" {
		sb.WriteString("<br>")
		sb.WriteString(html.EscapeString(view.Description))
	}
	sb.WriteString("<br><br>")
	sb.WriteString("<font point-size=\"9\">")
	if cfg.Repo != "" {
		sb.WriteString("Repo: ")
		sb.WriteString(html.EscapeString(cfg.Repo))
		sb.WriteString("<br>")
	}
	sb.WriteString("Source: ")
	sb.WriteString(html.EscapeString(modelPath))
	sb.WriteString("<br>Last synced: ")
	sb.WriteString(html.EscapeString(timestamp))
	if cfg.Author != "" {
		sb.WriteString("<br>Author: ")
		sb.WriteString(html.EscapeString(cfg.Author))
	}
	sb.WriteString("<br>Generated by Bausteinsicht</font>")
	return sb.String()
}

// buildLegendLabel returns an HTML label for the legend box.
func buildLegendLabel(
	spec model.Specification,
	templates *drawio.TemplateSet,
	elemSet map[string]bool,
	flat map[string]*model.Element,
) string {
	// Collect kinds actually used in this view.
	usedKinds := make(map[string]bool)
	for id := range elemSet {
		if elem, ok := flat[id]; ok {
			usedKinds[elem.Kind] = true
		}
	}

	// Sort kinds for deterministic output.
	kinds := make([]string, 0, len(usedKinds))
	for k := range usedKinds {
		kinds = append(kinds, k)
	}
	sort.Strings(kinds)

	allStyles := templates.GetAllStyles()

	var sb strings.Builder
	sb.WriteString("<b>Legend</b>")

	for _, kind := range kinds {
		ekind, ok := spec.Elements[kind]
		if !ok {
			continue
		}

		color := extractFillColor(allStyles, kind)
		sb.WriteString("<br>")
		fmt.Fprintf(&sb,
			"<font color=\"%s\">\u25a0</font> %s",
			html.EscapeString(color),
			html.EscapeString(ekind.Notation),
		)
	}

	return sb.String()
}

// extractFillColor extracts the fillColor from a template style string.
// Returns a default gray if not found.
func extractFillColor(allStyles map[string]drawio.TemplateStyle, kind string) string {
	ts, ok := allStyles[kind]
	if !ok {
		return "#666666"
	}
	for _, part := range strings.Split(ts.Style, ";") {
		if strings.HasPrefix(part, "fillColor=") {
			return strings.TrimPrefix(part, "fillColor=")
		}
	}
	return "#666666"
}

// createInfoBox creates a non-model mxCell info box at the given position.
func createInfoBox(root *etree.Element, id, label string, x, y, width float64) {
	obj := root.CreateElement("object")
	obj.CreateAttr("label", label)
	obj.CreateAttr("id", id)

	cell := obj.CreateElement("mxCell")
	cell.CreateAttr("style", "rounded=0;whiteSpace=wrap;html=1;fillColor=#f5f5f5;strokeColor=none;fontColor=#333333;fontSize=10;align=left;verticalAlign=top;")
	cell.CreateAttr("vertex", "1")
	cell.CreateAttr("parent", "1")

	geo := cell.CreateElement("mxGeometry")
	geo.CreateAttr("x", fmt.Sprintf("%.0f", x))
	geo.CreateAttr("y", fmt.Sprintf("%.0f", y))
	geo.CreateAttr("width", fmt.Sprintf("%.0f", width))
	geo.CreateAttr("height", "120")
	geo.CreateAttr("as", "geometry")
}

// computeMaxY finds the bottom-most Y coordinate of elements on the page,
// excluding the specified cell IDs (used to ignore metadata/legend boxes).
func computeMaxY(page *drawio.Page, excludeIDs ...string) float64 {
	exclude := make(map[string]bool, len(excludeIDs))
	for _, id := range excludeIDs {
		exclude[id] = true
	}

	maxY := 0.0
	root := page.Root()
	if root == nil {
		return maxY
	}
	for _, obj := range root.ChildElements() {
		// Skip excluded cells.
		if id := obj.SelectAttrValue("id", ""); exclude[id] {
			continue
		}
		cell := obj.FindElement("mxCell")
		if cell == nil {
			if obj.Tag == "mxCell" {
				cell = obj
			} else {
				continue
			}
		}
		geo := cell.FindElement("mxGeometry")
		if geo == nil {
			continue
		}
		y := parseFloat(geo.SelectAttrValue("y", "0"))
		h := parseFloat(geo.SelectAttrValue("height", "0"))
		if bottom := y + h; bottom > maxY {
			maxY = bottom
		}
	}
	return maxY
}

// computeContentWidth finds the rightmost X+Width of elements on the page,
// excluding the specified cell IDs.
func computeContentWidth(page *drawio.Page, excludeIDs ...string) float64 {
	exclude := make(map[string]bool, len(excludeIDs))
	for _, id := range excludeIDs {
		exclude[id] = true
	}

	maxRight := 0.0
	root := page.Root()
	if root == nil {
		return maxRight
	}
	for _, obj := range root.ChildElements() {
		if id := obj.SelectAttrValue("id", ""); exclude[id] {
			continue
		}
		cell := obj.FindElement("mxCell")
		if cell == nil {
			if obj.Tag == "mxCell" {
				cell = obj
			} else {
				continue
			}
		}
		geo := cell.FindElement("mxGeometry")
		if geo == nil {
			continue
		}
		x := parseFloat(geo.SelectAttrValue("x", "0"))
		w := parseFloat(geo.SelectAttrValue("width", "0"))
		if right := x + w; right > maxRight {
			maxRight = right
		}
	}
	return maxRight
}

// parseFloat parses a string to float64, returning 0 on failure.
func parseFloat(s string) float64 {
	f, _ := strconv.ParseFloat(s, 64)
	return f
}
