package diagram

import (
	"fmt"
	"strings"
	"time"
)

// WrapDiagramsInMarkdown wraps multiple Mermaid diagrams in a Markdown document.
// viewKeys: ordered list of view keys
// diagrams: map of view key → Mermaid diagram code (without outer backticks)
func WrapDiagramsInMarkdown(viewKeys []string, diagrams map[string]string, viewTitles map[string]string) string {
	var b strings.Builder

	b.WriteString("# Architecture Diagrams\n\n")
	b.WriteString("> Auto-generated by bausteinsicht — do not edit manually.\n")
	fmt.Fprintf(&b, "> Last updated: %s\n\n", time.Now().UTC().Format(time.RFC3339))

	for _, viewKey := range viewKeys {
		diagramCode, exists := diagrams[viewKey]
		if !exists || diagramCode == "" {
			continue
		}

		title := viewKey
		if customTitle, ok := viewTitles[viewKey]; ok {
			title = customTitle
		}

		fmt.Fprintf(&b, "## %s\n\n", title)
		b.WriteString("```mermaid\n")
		b.WriteString(diagramCode)
		b.WriteString("\n```\n\n")
	}

	return b.String()
}
