package diagram

import (
	"strings"
	"testing"
)

func TestWrapDiagramsInMarkdown(t *testing.T) {
	diagrams := map[string]string{
		"context": "C4Context\n    title Context View\n    Person(user, \"User\")",
		"container": "C4Container\n    title Container View\n    Container(api, \"API\")",
	}
	viewTitles := map[string]string{
		"context": "System Context",
		"container": "Container Architecture",
	}
	viewKeys := []string{"context", "container"}

	output := WrapDiagramsInMarkdown(viewKeys, diagrams, viewTitles)

	// Check header
	if !strings.Contains(output, "# Architecture Diagrams") {
		t.Fatal("missing header")
	}

	// Check metadata
	if !strings.Contains(output, "Auto-generated by bausteinsicht") {
		t.Fatal("missing metadata")
	}
	if !strings.Contains(output, "Last updated:") {
		t.Fatal("missing timestamp")
	}

	// Check sections
	if !strings.Contains(output, "## System Context") {
		t.Fatal("missing context section title")
	}
	if !strings.Contains(output, "## Container Architecture") {
		t.Fatal("missing container section title")
	}

	// Check Mermaid blocks
	if !strings.Contains(output, "```mermaid") {
		t.Fatal("missing mermaid block opener")
	}
	if !strings.Contains(output, "C4Context") {
		t.Fatal("missing context diagram")
	}
	if !strings.Contains(output, "C4Container") {
		t.Fatal("missing container diagram")
	}
}

func TestWrapDiagramsInMarkdownEmpty(t *testing.T) {
	diagrams := map[string]string{}
	viewTitles := map[string]string{}
	viewKeys := []string{}

	output := WrapDiagramsInMarkdown(viewKeys, diagrams, viewTitles)

	// Should still have header and metadata
	if !strings.Contains(output, "# Architecture Diagrams") {
		t.Fatal("missing header")
	}
	if !strings.Contains(output, "Auto-generated by bausteinsicht") {
		t.Fatal("missing metadata")
	}
}

func TestWrapDiagramsInMarkdownSingleView(t *testing.T) {
	diagrams := map[string]string{
		"context": "C4Context\n    Person(user, \"User\")",
	}
	viewTitles := map[string]string{
		"context": "Architecture",
	}
	viewKeys := []string{"context"}

	output := WrapDiagramsInMarkdown(viewKeys, diagrams, viewTitles)

	if !strings.Contains(output, "## Architecture") {
		t.Fatal("missing section title")
	}
	if !strings.Contains(output, "C4Context") {
		t.Fatal("missing diagram")
	}
}

func TestWrapDiagramsInMarkdownOrderPreserved(t *testing.T) {
	diagrams := map[string]string{
		"z": "Z",
		"a": "A",
		"m": "M",
	}
	viewTitles := map[string]string{
		"z": "Z View",
		"a": "A View",
		"m": "M View",
	}
	viewKeys := []string{"z", "a", "m"}

	output := WrapDiagramsInMarkdown(viewKeys, diagrams, viewTitles)

	// Check that order is preserved (Z before A before M)
	zPos := strings.Index(output, "## Z View")
	aPos := strings.Index(output, "## A View")
	mPos := strings.Index(output, "## M View")

	if zPos < 0 || aPos < 0 || mPos < 0 {
		t.Fatal("missing sections")
	}
	if !(zPos < aPos && aPos < mPos) {
		t.Fatal("view order not preserved")
	}
}
